// Turn a recorded journey into a runnable Playwright spec.
//
// The point is not to replace A11y Lens's own replay — it is that most teams
// already own Playwright, and a recording they can run in their existing CI is
// worth more than one locked inside another tool.
//
// The generated spec uses the SAME ranked selectors the recorder captured, so it
// inherits the durability: getByTestId / getByRole(name) first, a CSS path only
// when nothing better exists. Positional selectors are emitted with a warning
// comment, because a spec that silently depends on div:nth-of-type(3) is a
// maintenance trap.

const escapeReSrc = (s) => String(s).replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
const q = (s) => `'${String(s).replace(/\\/g, "\\\\").replace(/'/g, "\\'")}'`;

// Best available locator expression for a recorded target.
function locatorExpr(target) {
  const sels = (target && target.selectors) || [];
  const pick = (by) => sels.find((s) => s.by === by);

  const testid = pick("testid");
  if (testid) return { expr: `page.getByTestId(${q(testid.value)})`, tier: "testid", stable: true };

  const role = pick("role");
  if (role && role.name) return { expr: `page.getByRole(${q(role.role)}, { name: ${q(role.name)} })`, tier: "role", stable: true };
  if (role) return { expr: `page.getByRole(${q(role.role)})`, tier: "role", stable: true };

  const label = pick("label");
  if (label) return { expr: `page.getByLabel(${q(label.value)})`, tier: "label", stable: true };

  const ph = pick("placeholder");
  if (ph) return { expr: `page.getByPlaceholder(${q(ph.value)})`, tier: "placeholder", stable: true };

  const text = pick("text");
  if (text) return { expr: `page.getByText(${q(text.value)}, { exact: true })`, tier: "text", stable: true };

  const tagText = pick("tagText");
  if (tagText) return { expr: `page.locator(${q(tagText.tag || "*")}, { hasText: ${q(tagText.value)} })`, tier: "tagText", stable: true };

  const css = sels.find((s) => s.by === "css");
  if (css) return { expr: `page.locator(${q(css.value)})`, tier: "css", stable: false };

  const xp = pick("xpath");
  if (xp) return { expr: `page.locator(${q("xpath=" + xp.value)})`, tier: "xpath", stable: false };

  return null;
}

function label(target, fallback) {
  return (target && (target.name || target.text || target.tag)) || fallback;
}

export function generateSpec(recording, opts = {}) {
  const name = opts.name || "Recorded journey";
  const steps = Array.isArray(recording.steps) ? recording.steps : [];
  const checkAxe = opts.axe !== false;
  const lines = [];
  const warnings = [];
  let unstable = 0, masked = 0;

  lines.push(`import { test, expect } from '@playwright/test';`);
  if (checkAxe) lines.push(`import AxeBuilder from '@axe-core/playwright';`);
  lines.push("");
  lines.push(`// Generated by A11y Lens from a recorded journey.`);
  lines.push(`// Selectors are ordered by durability: test id > role + accessible name >`);
  lines.push(`// label > text > CSS. Anything marked UNSTABLE below had no accessible`);
  lines.push(`// identity to bind to — that is worth fixing in the app, not the test.`);
  lines.push("");
  lines.push(`test(${q(name)}, async ({ page }) => {`);

  const maskedSteps = steps.filter((s) => s.masked);
  if (maskedSteps.length) {
    masked = maskedSteps.length;
    lines.push(`  // ${masked} field(s) were masked at capture (passwords / OTP / card data).`);
    lines.push(`  // Supply them from environment variables — never commit real values.`);
  }

  const checkpoints = new Set(
    (Array.isArray(recording.checkpoints) && recording.checkpoints.length)
      ? recording.checkpoints
      : steps.filter((s) => s.checkpoint).map((s) => s.i)
  );

  for (const step of steps) {
    const t = step.type;

    if (t === "navigate") {
      const meta = step.urlMeta;
      if (step.manual && step.url) {
        lines.push(`  await page.goto(${q(step.url)});`);
        // Assert the ROUTE, never the literal URL: a dynamic id makes an exact
        // match fail on the very next run against different data.
        if (meta && meta.regexPattern && meta.hasParams) {
          lines.push(`  await expect(page).toHaveURL(new RegExp(${q(meta.regexPattern)}));`);
        } else if (meta && meta.pathTemplate) {
          lines.push(`  await expect(page).toHaveURL(new RegExp(${q(escapeReSrc(meta.pathTemplate))}));`);
        }
      } else {
        lines.push(`  await page.waitForLoadState('domcontentloaded');`);
      }
    } else if (step.masked) {
      const l = locatorExpr(step.target);
      const envName = `A11Y_SECRET_${step.i}`;
      lines.push(`  // masked at capture — value never stored`);
      lines.push(l ? `  await ${l.expr}.fill(process.env.${envName} ?? '');`
                   : `  // TODO: supply ${envName} (no selector was captured for this field)`);
    } else if (t === "press" && !step.target) {
      lines.push(`  await page.keyboard.press(${q(step.key || "Enter")});`);
    } else {
      const l = locatorExpr(step.target);
      if (!l) { lines.push(`  // SKIPPED ${t}: no usable selector was recorded`); continue; }
      if (!l.stable) {
        unstable++;
        warnings.push(`Step ${step.i} (${t} on "${label(step.target, t)}") resolves only by ${l.tier} — no role, name, label or test id.`);
        lines.push(`  // UNSTABLE (${l.tier}): "${label(step.target, t)}" has no accessible identity — see WCAG 4.1.2`);
      }
      switch (t) {
        case "click":   lines.push(`  await ${l.expr}.click();`); break;
        case "fill":    lines.push(`  await ${l.expr}.fill(${q(step.value ?? "")});`); break;
        case "check":   lines.push(`  await ${l.expr}.check();`); break;
        case "uncheck": lines.push(`  await ${l.expr}.uncheck();`); break;
        case "press":   lines.push(`  await ${l.expr}.press(${q(step.key || "Enter")});`); break;
        case "select": {
          const v = Array.isArray(step.values) && step.values.length ? step.values[0]
                  : (Array.isArray(step.labels) && step.labels.length ? step.labels[0] : "");
          lines.push(`  await ${l.expr}.selectOption(${q(v)});`);
          break;
        }
        case "upload":  lines.push(`  // upload steps cannot be replayed automatically — set a file path here`); break;
        default:        lines.push(`  // unsupported step type: ${t}`);
      }
    }

    if (checkAxe && checkpoints.has(step.i)) {
      lines.push(`  {`);
      lines.push(`    const results = await new AxeBuilder({ page })`);
      lines.push(`      .withTags(['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa'])`);
      lines.push(`      .analyze();`);
      lines.push(`    expect(results.violations, 'accessibility violations at step ${step.i}').toEqual([]);`);
      lines.push(`  }`);
    }
  }

  lines.push(`});`);
  lines.push("");

  return {
    code: lines.join("\n"),
    stats: { steps: steps.length, checkpoints: checkpoints.size, unstable, masked },
    warnings,
  };
}
